//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xemio.SmartNotes.Client.Windows.Implementations.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xemio.SmartNotes.Client.Windows.Implementations.Tasks.TaskMessages", typeof(TaskMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing avatar....
        /// </summary>
        internal static string ChangeAvatarTask {
            get {
                return ResourceManager.GetString("ChangeAvatarTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing the avatar..
        /// </summary>
        internal static string ChangeAvatarTaskFailed {
            get {
                return ResourceManager.GetString("ChangeAvatarTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder....
        /// </summary>
        internal static string CreateFolderTask {
            get {
                return ResourceManager.GetString("CreateFolderTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating the folder..
        /// </summary>
        internal static string CreateFolderTaskFailed {
            get {
                return ResourceManager.GetString("CreateFolderTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting folder &apos;{0}&apos; ....
        /// </summary>
        internal static string DeleteFolderTask {
            get {
                return ResourceManager.GetString("DeleteFolderTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting the folder &apos;{0}&apos;..
        /// </summary>
        internal static string DeleteFolderTaskFailed {
            get {
                return ResourceManager.GetString("DeleteFolderTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing folder &apos;{0}&apos;....
        /// </summary>
        internal static string EditFolderTask {
            get {
                return ResourceManager.GetString("EditFolderTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while editing the folder &apos;{0}&apos;..
        /// </summary>
        internal static string EditFolderTaskFailed {
            get {
                return ResourceManager.GetString("EditFolderTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing..
        /// </summary>
        internal static string ErrorInTask {
            get {
                return ResourceManager.GetString("ErrorInTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving folder &apos;{0}&apos; ....
        /// </summary>
        internal static string MoveFolderTask {
            get {
                return ResourceManager.GetString("MoveFolderTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while moving the folder &apos;{0}&apos;..
        /// </summary>
        internal static string MoveFolderTaskFailed {
            get {
                return ResourceManager.GetString("MoveFolderTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving note &apos;{0}&apos; ....
        /// </summary>
        internal static string MoveNoteTask {
            get {
                return ResourceManager.GetString("MoveNoteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while moving the note &apos;{0}&apos;..
        /// </summary>
        internal static string MoveNoteTaskFailed {
            get {
                return ResourceManager.GetString("MoveNoteTaskFailed", resourceCulture);
            }
        }
    }
}
